sudo: required
services:
  -docker

before_install:
  - docker build -t robertotesta/react-test -f ./client/Dockerfile.dev .

script:
  - docker run -e CI=true robertotesta/react-test npm test -- --coverage

after_success:
  - docker build -t robertotesta/multi-client ./client
  - docker build -t robertotesta/multi-nginx ./nginx
  - docker build -t robertotesta/multi-server ./server
  - docker build -t robertotesta/multi-worker ./worker